load('//:subdir_glob.bzl', 'subdir_glob')

cxx_binary(
  name = '{{ cookiecutter.Repo }}',
  header_namespace = '{{ cookiecutter.Repo }}',
  headers = subdir_glob([
    ('{{ cookiecutter.Repo }}/include', '**/*.hpp'),
  ]),
  srcs = glob([
    '{{ cookiecutter.Repo }}/src/**/*.cpp',
  ]),
  deps = [
    '//mathutils:mathutils',
  ],
)
